export const currencies = [
  { code: 'Israeli Shekel', symbol: '₪' },
  { code: 'USD', symbol: '$' },
  { code: 'Australian Dollar', symbol: 'AU$' },
  { code: 'Botswana Pula', symbol: 'BWP' },
  { code: 'British Pounds', symbol: '£' },
  { code: 'Canadian Dollar', symbol: 'CA$' },
  { code: 'Danish Krone', symbol: 'kr' },
  { code: 'Egyptian Pounds', symbol: 'E£' },
  { code: 'Emirati Dirham', symbol: 'د.إ' },
  { code: 'EUR', symbol: '€' },
  { code: 'Fijian Dollar', symbol: 'FJ$' },
  { code: 'Icelandic Króna', symbol: 'ISK' },
  { code: 'Indian Rupee', symbol: '₹' },
  { code: 'Jamaican Dollar', symbol: 'JA$' },
  { code: 'Jordanian Dinar', symbol: 'دينار أردني' },
  { code: 'Kenyan Shilling', symbol: 'KSh' },
  { code: 'Kuwaiti Dinar', symbol: 'د.ك' },
  { code: 'Lesotho Loti', symbol: 'L' },
  { code: 'Maldivian Rufiyaa', symbol: '. ރ' },
  { code: 'Mexican Peso', symbol: 'Mex$' },
  { code: 'Nepalese Rupee', symbol: 'रु॰' },
  { code: 'New Zealand Dollar', symbol: 'NZD' },
  { code: 'Norwegian Krone', symbol: 'kr' },
  { name: 'Oman', code: 'Omani Rial', symbol: 'OMR' },
  { code: 'Pakistani Rupee', symbol: 'PKR' },
  { code: 'Philippino Peso', symbol: '₱' },
  { name: 'Qatar', code: 'Qatari Riyal', symbol: 'QR' },
  { name: 'Saudi Arabia', code: 'Saudi Riyal', symbol: 'ر. سSAR' },
  { name: 'Seychelles', code: 'Seychellois Rupee', symbol: 'SRe' },
  { code: 'South African Rands', symbol: 'R' },
  { name: 'Sri Lanka', code: 'Sri Lankan Rupee', symbol: 'රු.' },
  { name: 'Trinidad and Tobago', code: 'Trinidad and Tobago', symbol: 'TT$' },
  { code: 'Zambian Kwacha', symbol: 'ZK' },
];

export const plans = [
  { plan: 'Retirement', id:1},
  { plan: 'Energy', id: 2 },
  { plan: 'Commodities', id: 3 },
  { plan: 'Forex', id: 4 },
  { plan: 'Stocks', id: 5 },
  { plan: 'Agriculture', id: 6 },
  { plan: 'CrudeOil', id: 7 },
  { plan: 'Marijuana', id: 8 },
  { plan: 'Crypto', id: 9 },
  { plan: 'PreciousMetal', id: 10 },
  { plan: 'Gold', id: 11 },
  { plan: 'Maganese', id: 12 },
  { plan: 'Silver', id: 13 },
];
